language: java
sudo: false
dist: trusty

addons:
  apt:
    update: true

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE meleride;'

install: script/install
script: script/script

jdk:
  - openjdk8
  - oraclejdk8

notifications:
  email: false
