#!/usr/bin/env bash

wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar && java -jar BuildTools.jar --rev 1.9
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
